## -----------------------------------------------------------------------------
## GitLab CI configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2023-05-11
## -----------------------------------------------------------------------------

---
image: alpine:latest

before_script:
  - apk add --no-cache go curl

stages:
  - build

build-go:
  stage: build
  script:
    - mkdir build/
    - go build -a -buildmode=exe -trimpath -o build/moodle-maxima-pool
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "build/moodle-maxima-pool" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/linux-x86_64/${CI_COMMIT_TAG:=latest}/moodle-maxima-pool"'
  only:
    - main
...
