##------------------------------------------------------------------------------
## GitLab CI Go
##
## @author     Lars Thoms
## @date       2022-08-17
##------------------------------------------------------------------------------

image: alpine:latest

before_script:
  - apk add --no-cache go upx curl

stages:
  - build

build-go:
  stage: build
  script:
    - go build -ldflags="-s -w" -trimpath maxima-pool.go
    - upx --brute maxima-pool
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "maxima-pool" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/linux-x86_64/${CI_COMMIT_TAG:=latest}/maxima-pool"'
